# Generated by Django 3.0.3 on 2020-02-23 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('write', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_range',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='write.Subject_range'),
        ),
    ]
